const profiles = [
    { name: "Gregorius Natanael Anggalaksmana", role: "Sponext", img: "/user.png", division: "NTC" },
    { name: "Fajriah Khairunnisa", role: "Finad", img: "/user.png", division: "NTC" },
    { name: "Kusumastuti Windria", role: "Sosbrand", img: "/user.png", division: "NTC" },
    { name: "Muhammad Gian Yudha Prawira", role: "Microcontroller", img: "/user.png", division: "EPR" },
    { name: "Fatharanni Faza", role: "Electrical Design", img: "/user.png", division: "EPR" },
    { name: "Muhammad Fazayyan Razzan Izzuddin", role: "Electrical Design", img: "/user.png", division: "EPR" },
    { name: "Kaka Agastya Herlambang Wahyudi", role: "Web Development", img: "/user.png", division: "EPR" },
    { name: "Muhammad Abdullah", role: "Programming", img: "/user.png", division: "EPR" },
    { name: "Rizwan Ahmad Maulana", role: "Mechanical Production", img: "/user.png", division: "MEC" },
    { name: "Fazlee Mawla Nasution", role: "Mechanical Production", img: "/user.png", division: "MEC" },
    { name: "Rizqi Setya Cahyadi", role: "Mechanical Design", img: "/user.png", division: "MEC" },
    { name: "M. Fakhri Tuffaahatii", role: "Mechanical Design", img: "/user.png", division: "MEC" },
    { name: "M. Caesar Yudhistira Prabowo", role: "Mechanical Design", img: "/user.png", division: "MEC" },
  ];